// <auto-generated />
using System;
using CleanArchAcceleratorTools.Examples.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchAcceleratorTools.Examples.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_ADDRESS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_CITY");

                    b.Property<string>("Complement")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TX_COMPLEMENT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CREATION");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TX_NEIGHBORHOOD");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TX_NUMBER");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TX_POSTAL_CODE");

                    b.Property<string>("StreetAvenue")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TX_STREET_AVENUE");

                    b.HasKey("Id")
                        .HasName("SQ_ADDRESS");

                    b.HasIndex("CityId");

                    b.ToTable("TB_ADDRESS", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_CITY");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CD_CITY");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CREATION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NM_CITY");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_STATE");

                    b.HasKey("Id")
                        .HasName("SQ_CITY");

                    b.HasIndex("StateId");

                    b.ToTable("TB_CITY", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_COUNTRY");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CD_COUNTRY");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CREATION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NM_COUNTRY");

                    b.HasKey("Id")
                        .HasName("SQ_COUNTRY");

                    b.ToTable("TB_COUNTRY", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_STATE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TX_ABBREVIATION");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CD_STATE");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_COUNTRY");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CREATION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NM_STATE");

                    b.HasKey("Id")
                        .HasName("SQ_STATE");

                    b.HasIndex("CountryId");

                    b.ToTable("TB_STATE", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_COURSE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DT_CREATION");

                    b.Property<long?>("InstructorId")
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_INSTRUCTOR");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TX_TITLE");

                    b.HasKey("Id")
                        .HasName("SQ_COURSE");

                    b.HasIndex("InstructorId");

                    b.ToTable("TB_COURSE", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_LESSON");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CREATION");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time")
                        .HasColumnName("DT_DURATION");

                    b.Property<long?>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_MODULE");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TX_TITLE");

                    b.HasKey("Id")
                        .HasName("SQ_LESSON");

                    b.HasIndex("ModuleId");

                    b.ToTable("TB_LESSON", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_MODULE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_COURSE");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CREATION");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TX_NAME");

                    b.HasKey("Id")
                        .HasName("SQ_MODULE");

                    b.HasIndex("CourseId");

                    b.ToTable("TB_MODULE", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Instructors.Instructor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_INSTRUCTOR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CREATION");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TX_FULL_NAME");

                    b.HasKey("Id")
                        .HasName("SQ_INSTRUCTOR");

                    b.ToTable("TB_INSTRUCTOR", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Instructors.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_PROFILE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_ADDRESS");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TX_BIO");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CREATION");

                    b.Property<long?>("InstructorId")
                        .HasColumnType("bigint")
                        .HasColumnName("SQ_INSTRUCTOR");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TX_LINKEDIN");

                    b.HasKey("Id")
                        .HasName("SQ_PROFILE");

                    b.HasIndex("AddressId");

                    b.HasIndex("InstructorId")
                        .IsUnique()
                        .HasFilter("[SQ_INSTRUCTOR] IS NOT NULL");

                    b.ToTable("TB_PROFILE", (string)null);
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.Address", b =>
                {
                    b.HasOne("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.City", b =>
                {
                    b.HasOne("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.State", b =>
                {
                    b.HasOne("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Course", b =>
                {
                    b.HasOne("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Instructors.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Lesson", b =>
                {
                    b.HasOne("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Module", null)
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Module", b =>
                {
                    b.HasOne("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Course", null)
                        .WithMany("Modules")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Instructors.Profile", b =>
                {
                    b.HasOne("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Addresses.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Instructors.Instructor", null)
                        .WithOne("Profile")
                        .HasForeignKey("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Instructors.Profile", "InstructorId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Courses.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("CleanArchAcceleratorTools.Examples.Domain.Aggregates.Instructors.Instructor", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
