//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchAcceleratorTools.Domain.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchAcceleratorTools.Domain.Messages.DomainMessages", typeof(DomainMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections are not supported for &quot;{0}&quot;.
        /// </summary>
        public static string CollectionsNotSupportedFor {
            get {
                return ResourceManager.GetString("CollectionsNotSupportedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; does not exist in the DataTable..
        /// </summary>
        public static string ColumnDoesNotExistInDataTable {
            get {
                return ResourceManager.GetString("ColumnDoesNotExistInDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column order must be defined..
        /// </summary>
        public static string ColumnOrderMustBeDefined {
            get {
                return ResourceManager.GetString("ColumnOrderMustBeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration type &apos;{0}&apos; is not assignable to &apos;{2}&apos; for entity &apos;{1}&apos;..
        /// </summary>
        public static string ConfigurationTypeNotAssignableForEntity {
            get {
                return ResourceManager.GetString("ConfigurationTypeNotAssignableForEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ::: {1}.
        /// </summary>
        public static string DatedNotificationTemplate {
            get {
                return ResourceManager.GetString("DatedNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm:ss.fff.
        /// </summary>
        public static string DatedNotificationTimestampFormat {
            get {
                return ResourceManager.GetString("DatedNotificationTimestampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred..
        /// </summary>
        public static string DefaultUnhandledErrorMessage {
            get {
                return ResourceManager.GetString("DefaultUnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity is not configured in the DbContext..
        /// </summary>
        public static string EntityNotConfiguredInDbContext {
            get {
                return ResourceManager.GetString("EntityNotConfiguredInDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityValidation.
        /// </summary>
        public static string EntityValidationKey {
            get {
                return ResourceManager.GetString("EntityValidationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity with id {0} not found..
        /// </summary>
        public static string EntityWithIdNotFound {
            get {
                return ResourceManager.GetString("EntityWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred when persisting data..
        /// </summary>
        public static string ErrorPersistingData {
            get {
                return ResourceManager.GetString("ErrorPersistingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |||.
        /// </summary>
        public static string ExceptionMessageSeparator {
            get {
                return ResourceManager.GetString("ExceptionMessageSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{1}&quot; does not exist in the entity &quot;{0}&quot;.
        /// </summary>
        public static string FieldDoesNotExistInEntity {
            get {
                return ResourceManager.GetString("FieldDoesNotExistInEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandleAsync on type &quot;{0}&quot; returned null or invalid Task..
        /// </summary>
        public static string HandleAsyncReturnedNullOrInvalidTask {
            get {
                return ResourceManager.GetString("HandleAsyncReturnedNullOrInvalidTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operator &apos;{0}&apos;.
        /// </summary>
        public static string InvalidComparisonOperator {
            get {
                return ResourceManager.GetString("InvalidComparisonOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order direction in dynamic sort..
        /// </summary>
        public static string InvalidOrderDirectionInDynamicSort {
            get {
                return ResourceManager.GetString("InvalidOrderDirectionInDynamicSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is not valid for property &quot;{1}&quot;..
        /// </summary>
        public static string InvalidPropertyAssign {
            get {
                return ResourceManager.GetString("InvalidPropertyAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot;  is not valid for property &quot;{1}. Only allowed &quot;({2})&quot;.
        /// </summary>
        public static string InvalidPropertyAssignWithAllowed {
            get {
                return ResourceManager.GetString("InvalidPropertyAssignWithAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG.
        /// </summary>
        public static string LogLabelDebug {
            get {
                return ResourceManager.GetString("LogLabelDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string LogLabelError {
            get {
                return ResourceManager.GetString("LogLabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        public static string LogLabelInformation {
            get {
                return ResourceManager.GetString("LogLabelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACE.
        /// </summary>
        public static string LogLabelTrace {
            get {
                return ResourceManager.GetString("LogLabelTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string LogLabelWarning {
            get {
                return ResourceManager.GetString("LogLabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No handler registered. Expected service &quot;{0}&quot; for request type &quot;{1}&quot;..
        /// </summary>
        public static string NoHandlerRegisteredExpectedService {
            get {
                return ResourceManager.GetString("NoHandlerRegisteredExpectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more parameters available.
        /// </summary>
        public static string NoMoreParametersAvailable {
            get {
                return ResourceManager.GetString("NoMoreParametersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered context found for key &apos;{0}&apos;..
        /// </summary>
        public static string NoRegisteredContextFoundForKey {
            get {
                return ResourceManager.GetString("NoRegisteredContextFoundForKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No working contexts..
        /// </summary>
        public static string NoWorkingContexts {
            get {
                return ResourceManager.GetString("NoWorkingContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; operator can only be applied to string fields. Field &apos;{1}&apos; is of type &apos;{2}&apos;..
        /// </summary>
        public static string OperatorOnlyForStringFields {
            get {
                return ResourceManager.GetString("OperatorOnlyForStringFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters &apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos; and &apos;{3}&apos; must be greater than 0..
        /// </summary>
        public static string ParallelParametersMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ParallelParametersMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; cannot be empty.
        /// </summary>
        public static string PropertyCannotBeEmpty {
            get {
                return ResourceManager.GetString("PropertyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property&quot;{0}&quot; cannot be null.
        /// </summary>
        public static string PropertyCannotBeNull {
            get {
                return ResourceManager.GetString("PropertyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list &quot;{0}&quot; cannot contains null values.
        /// </summary>
        public static string PropertyListCannotContainsNullValue {
            get {
                return ResourceManager.GetString("PropertyListCannotContainsNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; does not have a column mapping in the database..
        /// </summary>
        public static string PropertyMissingColumnMapping {
            get {
                return ResourceManager.GetString("PropertyMissingColumnMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; was not found on type {1}.
        /// </summary>
        public static string PropertyNotFoundOnType {
            get {
                return ResourceManager.GetString("PropertyNotFoundOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some entities were not found, ids: {0}..
        /// </summary>
        public static string SomeEntitiesWereNotFoundIds {
            get {
                return ResourceManager.GetString("SomeEntitiesWereNotFoundIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch size: {0}.
        /// </summary>
        public static string TraceBatchSize {
            get {
                return ResourceManager.GetString("TraceBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing parallelism.
        /// </summary>
        public static string TraceInitializingParallelism {
            get {
                return ResourceManager.GetString("TraceInitializingParallelism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration: {0}.
        /// </summary>
        public static string TraceIterationLabel {
            get {
                return ResourceManager.GetString("TraceIterationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum threads: {0}, Processes per thread: {1}.
        /// </summary>
        public static string TraceParallelismDetails {
            get {
                return ResourceManager.GetString("TraceParallelismDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing iteration range.
        /// </summary>
        public static string TraceProcessingIterationRange {
            get {
                return ResourceManager.GetString("TraceProcessingIterationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1} of {2}.
        /// </summary>
        public static string TraceProcessingIterationRangeDetails {
            get {
                return ResourceManager.GetString("TraceProcessingIterationRangeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A query has finished.
        /// </summary>
        public static string TraceQueryFinished {
            get {
                return ResourceManager.GetString("TraceQueryFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total records: {0}.
        /// </summary>
        public static string TraceTotalRecords {
            get {
                return ResourceManager.GetString("TraceTotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total required iterations: {0}.
        /// </summary>
        public static string TraceTotalRequiredIterations {
            get {
                return ResourceManager.GetString("TraceTotalRequiredIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; does not implement HandleAsync..
        /// </summary>
        public static string TypeDoesNotImplementHandleAsync {
            get {
                return ResourceManager.GetString("TypeDoesNotImplementHandleAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast type &quot;{0}&quot; to target type &quot;{1}&quot;..
        /// </summary>
        public static string UnableToCastTypeToTargetType {
            get {
                return ResourceManager.GetString("UnableToCastTypeToTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type &apos;{1}&apos; for property &apos;{0}&apos;..
        /// </summary>
        public static string UnsupportedTypeForProperty {
            get {
                return ResourceManager.GetString("UnsupportedTypeForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; must have an value greater than &quot;{1}&quot;.
        /// </summary>
        public static string ValueMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; must have an value greater than or equal to &quot;{1}&quot;.
        /// </summary>
        public static string ValueMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; must have an value less than &quot;{1}&quot;.
        /// </summary>
        public static string ValueMustBeLessThan {
            get {
                return ResourceManager.GetString("ValueMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; must have an value less than or equal to &quot;{1}&quot;.
        /// </summary>
        public static string ValueMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValueMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
    }
}
